kind: Service
apiVersion: v1
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: spring-boot
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot
      track: stable
  template:
    metadata:
      labels:
        app: spring-boot
        track: stable
    spec:
      containers:
      - name: spring-boot
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: prod
spec:
  rules:
    - host: prod.parloud.com
      http:
        paths:
          - backend:
              serviceName: spring-boot-service
              servicePort: 80
            path: /