kind: Service
apiVersion: v1
metadata:
  name: service-canary
spec:
  type: NodePort
  selector:
    app: spring-boot-canary
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-canary
  labels:
    app: spring-boot-canary
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: spring-boot-canary
      track: canary
  template:
    metadata:
      labels:
        app: spring-boot-canary
        track: canary
    spec:
      containers:
      - name: spring-boot-canary
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: canary
spec:
  rules:
    - host: canary.parloud.com
      http:
        paths:
          - backend:
              serviceName: service-canary
              servicePort: 80
            path: /